demo_project_sql/Models/Charge.cs
using System.ComponentModel.DataAnnotations;

namespace demo_project_sql.Models
{
    public class Charge
    {
        [Key, Required]
        public int Id { get; set; }

        public string ProcedureCode { get; set; }

        public string PatientName { get; set;}

        public DateTime EffectiveDate { get; set; }

        public bool isAnchor { get; set; }
    }
}

demo_project_sql/Models/ErrorViewModel.cs
namespace demo_project_sql.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

demo_project_sql/Controllers/ChargeController.cs
using demo_project_sql.Data;
using demo_project_sql.Models;
using Microsoft.AspNetCore.Mvc;

namespace demo_project_sql.Controllers
{
    public class ChargeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ChargeController(ApplicationDbContext db)
        {
            _db = db; 
            
        }
        public IActionResult Index()
        {
            IEnumerable<Models.Charge> objChargesList = _db.Charges;
            return View(objChargesList);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Edit(int? id)
        {
            var onecharge = _db.Charges.Find(id);
            return View(onecharge);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Charge obj)
        {
            _db.Charges.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Charge obj)
        {
            _db.Charges.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            var onecharge = _db.Charges.Find(id);
            return View(onecharge);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Charges.Find(id);
            _db.Charges.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

demo_project_sql/Controllers/HomeController.cs
using demo_project_sql.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace demo_project_sql.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

demo_project_sql/Views/Charge/Create.cshtml
@model Charge

<h1>Create</h1>

<form method="post">

    <div>
        <label asp-for="PatientName"></label>
        <input asp-for="PatientName" />
    </div>
    <div>
        <label asp-for="ProcedureCode"></label>
        <input asp-for="ProcedureCode" />
    </div>
    <div>
        <label asp-for="EffectiveDate"></label>
        <input asp-for="EffectiveDate" type="date" />
    </div>

    <div>
        <label asp-for="isAnchor"></label>
        <input asp-for="isAnchor" type="checkbox" />
    </div>
    <button type="submit">Create</button>
</form>

demo_project_sql/Views/Charge/Delete.cshtml
@model Charge

<h1>Delete</h1>

<form method="post" asp-action="DeletePOST">

    <input type="hidden" asp-for="Id" />

    <div>
        <label asp-for="PatientName"></label>
        <input asp-for="PatientName" />
    </div>
    <div>
        <label asp-for="ProcedureCode"></label>
        <input asp-for="ProcedureCode" />
    </div>
    <div>
        <label asp-for="EffectiveDate"></label>
        <input asp-for="EffectiveDate" type="date" />
    </div>

    <div>
        <label asp-for="isAnchor"></label>
        <input asp-for="isAnchor" type="checkbox" />
    </div>
    <button type="submit">Delete</button>
</form>

demo_project_sql/Views/Charge/Edit.cshtml
@model Charge

<h1>Delete</h1>

<form method="post">

    <div>
        <label asp-for="PatientName"></label>
        <input asp-for="PatientName" />
    </div>
    <div>
        <label asp-for="ProcedureCode"></label>
        <input asp-for="ProcedureCode" />
    </div>
    <div>
        <label asp-for="EffectiveDate"></label>
        <input asp-for="EffectiveDate" type="date" />
    </div>

    <div>
        <label asp-for="isAnchor"></label>
        <input asp-for="isAnchor" type="checkbox" />
    </div>
    <button type="submit">Update</button>
</form>

demo_project_sql/Views/Charge/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Charges Index</h1>
<table class=" table-striped  " style="width:100%">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                ProcedureCode
            </th>
            <th>
                PatientName
            </th>
            <th>
                EffectiveDate
            </th>
            <th>
                isAnchor
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>@obj.Id</td>
                <td>@obj.ProcedureCode</td>
                <td>@obj.PatientName</td>
                <td>@obj.EffectiveDate</td>
                <td>@obj.isAnchor</td>
            </tr>
        }
    </tbody>

</table>

demo_project_sql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

demo_project_sql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demo_project_sql</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/demo_project_sql.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">demo_project_sql</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Charge" asp-action="Index">Charge</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - demo_project_sql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>